# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "master"
      - "develop"

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Build
        run: go build cmd/main.go

      - name: Test
        run: go test cmd/main.go

  build-test-and-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Build
        run: go build cmd/main.go

      - name: Test
        run: go test cmd/main.go

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t rsouzaribeiro/pos_tech_fiap8soat .

      - name: Push Image Docker
        run: docker push rsouzaribeiro/pos_tech_fiap8soat

