# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "master"
      - "develop"

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Build
        run: go build main.go

      - name: Test
        run: go test main.go

  build-test-and-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Build
        run: go build -o apirest-go-gin main.go

      - name: Test
        run: go test main.go

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t rsouzaribeiro/api_alunos_estudos .

      - name: Push Image Docker
        run: docker push rsouzaribeiro/api_alunos_estudos

  deploy:
    needs: build-test-and-deploy
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull rsouzaribeiro/api_alunos_estudos:latest

      - name: Run docker container
        run: sudo docker run -d -p 8080:8080  rsouzaribeiro/api_alunos_estudos
